import { motion } from "framer-motion";
import { BellRing, CheckCircle2 } from "lucide-react";
import { AlertsPanel } from "@/components/dashboard/AlertsPanel";
import { Card, CardDescription, CardTitle } from "@/components/ui/Card";
import { useOfficeMonitor } from "@/hooks/useOfficeMonitor";

export function AlertsPage() {
  const { alerts, dismissAlert } = useOfficeMonitor();

  return (
    <div className="space-y-6 pb-8">
      <Card>
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <CardTitle className="flex items-center gap-2"><BellRing className="h-5 w-5 text-ember-400" />Alert Center</CardTitle>
            <CardDescription>Operational notices generated by the simulator and alert engine.</CardDescription>
          </div>
          <div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-sm text-emerald-200">
            <CheckCircle2 className="h-4 w-4" /> Live alert feed connected
          </div>
        </div>
      </Card>

      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
        <AlertsPanel alerts={alerts} onDismiss={dismissAlert} />
      </motion.div>
    </div>
  );
}
